// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQULG0NONh5aPBcFVHw3ZKEuGshjnu9Ek',
    appId: '1:901209154940:web:83a2095ffe58693131f0f9',
    messagingSenderId: '901209154940',
    projectId: 'flashcard-6edc2',
    authDomain: 'flashcard-6edc2.firebaseapp.com',
    storageBucket: 'flashcard-6edc2.appspot.com',
    measurementId: 'G-NWX0TTDHVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0jrO4OrBgaLqqGKM4TK1oqFpTjKgO-8',
    appId: '1:901209154940:android:0f9dd5bcc048b21031f0f9',
    messagingSenderId: '901209154940',
    projectId: 'flashcard-6edc2',
    storageBucket: 'flashcard-6edc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsQ9PEXI21TQdDCyhui_x9anFxuNeauI',
    appId: '1:901209154940:ios:71fe49cb6802310331f0f9',
    messagingSenderId: '901209154940',
    projectId: 'flashcard-6edc2',
    storageBucket: 'flashcard-6edc2.appspot.com',
    androidClientId: '901209154940-895g07d3d3491hvgt6834mvjqtc74c4k.apps.googleusercontent.com',
    iosClientId: '901209154940-cgn91gru777e3c82i21siire1vr7t368.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsQ9PEXI21TQdDCyhui_x9anFxuNeauI',
    appId: '1:901209154940:ios:fcaf6039af86e58d31f0f9',
    messagingSenderId: '901209154940',
    projectId: 'flashcard-6edc2',
    storageBucket: 'flashcard-6edc2.appspot.com',
    androidClientId: '901209154940-895g07d3d3491hvgt6834mvjqtc74c4k.apps.googleusercontent.com',
    iosClientId: '901209154940-snckol4qr9oopojomltq2hf4rtcpt4nq.apps.googleusercontent.com',
    iosBundleId: 'com.medicrecall.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQULG0NONh5aPBcFVHw3ZKEuGshjnu9Ek',
    appId: '1:901209154940:web:83a2095ffe58693131f0f9',
    messagingSenderId: '901209154940',
    projectId: 'flashcard-6edc2',
    authDomain: 'flashcard-6edc2.firebaseapp.com',
    storageBucket: 'flashcard-6edc2.appspot.com',
    measurementId: 'G-NWX0TTDHVC',
  );

}