name: Continuous Integration - Flutter

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flashcard
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: "stable"
          cache: true
      - name: Run Static Code Analysis
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flashcard
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: "stable"
          cache: true
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Run Flutter Tests
        run: flutter test
